name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore Amcart/backend/AmCart.Services.ProductAPI/AmCart.Services.ProductAPI.csproj

    - name: Build
      run: dotnet build Amcart/backend/AmCart.Services.ProductAPI/AmCart.Services.ProductAPI.csproj --no-restore